export default {
  tier: 'GOLD',
  queue: 'RANKED_SOLO_5x5',
  leagueId: 'e5367830-39dc-11e7-91a9-c81f66dacb22',
  name: "Lee Sin's Witch Hunters",
  entries: [
    {
      hotStreak: false,
      wins: 116,
      veteran: true,
      losses: 98,
      rank: 'II',
      playerOrTeamName: 'Váizki',
      inactive: false,
      playerOrTeamId: '99167272',
      freshBlood: false,
      leaguePoints: 76,
    },
    {
      hotStreak: false,
      wins: 24,
      veteran: false,
      losses: 36,
      rank: 'V',
      playerOrTeamName: 'Xayah The Wild',
      inactive: false,
      playerOrTeamId: '91167047',
      freshBlood: false,
      leaguePoints: 39,
    },
    {
      hotStreak: false,
      wins: 131,
      veteran: false,
      losses: 112,
      rank: 'V',
      playerOrTeamName: 'Elioze',
      inactive: false,
      playerOrTeamId: '40663554',
      freshBlood: false,
      leaguePoints: 42,
    },
    {
      hotStreak: false,
      wins: 658,
      veteran: true,
      losses: 659,
      rank: 'IV',
      playerOrTeamName: 'Kross Rp',
      inactive: false,
      playerOrTeamId: '35888389',
      freshBlood: false,
      leaguePoints: 41,
    },
    {
      hotStreak: false,
      wins: 5,
      veteran: false,
      losses: 8,
      rank: 'IV',
      playerOrTeamName: 'Kid Misaya',
      inactive: false,
      playerOrTeamId: '19666672',
      freshBlood: false,
      leaguePoints: 9,
    },
    {
      hotStreak: false,
      wins: 72,
      veteran: false,
      losses: 77,
      rank: 'IV',
      playerOrTeamName: 'Teile Schmeißen',
      inactive: false,
      playerOrTeamId: '26195209',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: false,
      wins: 51,
      veteran: false,
      losses: 51,
      rank: 'II',
      playerOrTeamName: 'jonas866',
      inactive: false,
      playerOrTeamId: '60827862',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: false,
      wins: 296,
      veteran: false,
      losses: 268,
      rank: 'V',
      playerOrTeamName: 'TheHellBo',
      inactive: false,
      playerOrTeamId: '84120039',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: false,
      wins: 7,
      veteran: false,
      losses: 5,
      rank: 'III',
      playerOrTeamName: 'Voidstep',
      inactive: false,
      playerOrTeamId: '79198560',
      freshBlood: false,
      leaguePoints: 24,
    },
    {
      hotStreak: false,
      wins: 50,
      veteran: false,
      losses: 45,
      rank: 'II',
      playerOrTeamName: 'No Game No Riven',
      inactive: false,
      playerOrTeamId: '98469187',
      freshBlood: false,
      leaguePoints: 67,
    },
    {
      hotStreak: false,
      wins: 87,
      veteran: false,
      losses: 91,
      rank: 'V',
      playerOrTeamName: 'FritsCrank ',
      inactive: false,
      playerOrTeamId: '24270393',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: false,
      wins: 27,
      veteran: false,
      losses: 15,
      rank: 'I',
      playerOrTeamName: 'Scannerfo',
      inactive: false,
      playerOrTeamId: '96647096',
      freshBlood: false,
      leaguePoints: 75,
    },
    {
      hotStreak: false,
      wins: 36,
      veteran: false,
      losses: 28,
      rank: 'I',
      playerOrTeamName: 'IAmNotDitto',
      inactive: false,
      playerOrTeamId: '84000835',
      freshBlood: false,
      leaguePoints: 75,
    },
    {
      hotStreak: false,
      wins: 124,
      veteran: false,
      losses: 137,
      rank: 'IV',
      playerOrTeamName: 'roages',
      inactive: false,
      playerOrTeamId: '39599333',
      freshBlood: false,
      leaguePoints: 45,
    },
    {
      hotStreak: false,
      wins: 208,
      veteran: true,
      losses: 181,
      rank: 'II',
      playerOrTeamName: 'großerBrüderKun',
      inactive: false,
      playerOrTeamId: '81503568',
      freshBlood: false,
      leaguePoints: 20,
    },
    {
      hotStreak: true,
      wins: 63,
      veteran: false,
      losses: 34,
      rank: 'I',
      playerOrTeamName: 'ChampRight06',
      inactive: false,
      playerOrTeamId: '94297055',
      freshBlood: false,
      leaguePoints: 75,
    },
    {
      hotStreak: false,
      wins: 203,
      veteran: true,
      losses: 208,
      rank: 'III',
      playerOrTeamName: 'Bush965',
      inactive: false,
      playerOrTeamId: '62920901',
      freshBlood: false,
      leaguePoints: 28,
    },
    {
      hotStreak: false,
      wins: 7,
      veteran: false,
      losses: 14,
      rank: 'V',
      playerOrTeamName: 'Elwiorion',
      inactive: false,
      playerOrTeamId: '43519696',
      freshBlood: false,
      leaguePoints: 49,
    },
    {
      hotStreak: false,
      wins: 323,
      veteran: true,
      losses: 333,
      rank: 'V',
      playerOrTeamName: 'TGB David Senpai',
      inactive: false,
      playerOrTeamId: '56958406',
      freshBlood: false,
      leaguePoints: 55,
    },
    {
      hotStreak: false,
      miniSeries: {
        wins: 1,
        losses: 1,
        target: 2,
        progress: 'WLN',
      },
      wins: 123,
      veteran: true,
      losses: 118,
      rank: 'II',
      playerOrTeamName: 'Qwerty Dvorak',
      inactive: false,
      playerOrTeamId: '35807718',
      freshBlood: false,
      leaguePoints: 81,
    },
    {
      hotStreak: false,
      wins: 87,
      veteran: false,
      losses: 76,
      rank: 'V',
      playerOrTeamName: 'ZeroSpellBound',
      inactive: false,
      playerOrTeamId: '19376562',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: false,
      wins: 10,
      veteran: false,
      losses: 8,
      rank: 'IV',
      playerOrTeamName: 'NGU Leptys',
      inactive: false,
      playerOrTeamId: '32331998',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: false,
      wins: 83,
      veteran: false,
      losses: 89,
      rank: 'III',
      playerOrTeamName: 'NooBTigEr',
      inactive: false,
      playerOrTeamId: '20984073',
      freshBlood: false,
      leaguePoints: 88,
    },
    {
      hotStreak: false,
      wins: 81,
      veteran: false,
      losses: 49,
      rank: 'I',
      playerOrTeamName: 'Laridric',
      inactive: false,
      playerOrTeamId: '50738239',
      freshBlood: false,
      leaguePoints: 75,
    },
    {
      hotStreak: false,
      wins: 104,
      veteran: true,
      losses: 102,
      rank: 'III',
      playerOrTeamName: 'FreddeM',
      inactive: false,
      playerOrTeamId: '19128968',
      freshBlood: false,
      leaguePoints: 37,
    },
    {
      hotStreak: false,
      wins: 10,
      veteran: false,
      losses: 9,
      rank: 'II',
      playerOrTeamName: 'IamWithU',
      inactive: false,
      playerOrTeamId: '23161036',
      freshBlood: false,
      leaguePoints: 4,
    },
    {
      hotStreak: false,
      wins: 4,
      veteran: false,
      losses: 7,
      rank: 'V',
      playerOrTeamName: 'ßasmon v2',
      inactive: false,
      playerOrTeamId: '61560444',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: false,
      wins: 95,
      veteran: false,
      losses: 82,
      rank: 'I',
      playerOrTeamName: 'Bjorganna',
      inactive: false,
      playerOrTeamId: '91637408',
      freshBlood: false,
      leaguePoints: 75,
    },
    {
      hotStreak: false,
      wins: 7,
      veteran: false,
      losses: 7,
      rank: 'IV',
      playerOrTeamName: 'VitaI Birne',
      inactive: false,
      playerOrTeamId: '41900637',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: false,
      wins: 62,
      veteran: false,
      losses: 59,
      rank: 'IV',
      playerOrTeamName: 'FrontColoss',
      inactive: false,
      playerOrTeamId: '86011668',
      freshBlood: false,
      leaguePoints: 43,
    },
    {
      hotStreak: false,
      miniSeries: {
        wins: 0,
        losses: 0,
        target: 2,
        progress: 'NNN',
      },
      wins: 14,
      veteran: false,
      losses: 2,
      rank: 'V',
      playerOrTeamName: 'Wannz',
      inactive: false,
      playerOrTeamId: '35726855',
      freshBlood: false,
      leaguePoints: 100,
    },
    {
      hotStreak: false,
      wins: 170,
      veteran: false,
      losses: 154,
      rank: 'II',
      playerOrTeamName: '6Bullets',
      inactive: false,
      playerOrTeamId: '58057311',
      freshBlood: false,
      leaguePoints: 17,
    },
    {
      hotStreak: false,
      wins: 27,
      veteran: false,
      losses: 10,
      rank: 'I',
      playerOrTeamName: 'Giorrailradana',
      inactive: false,
      playerOrTeamId: '96577827',
      freshBlood: false,
      leaguePoints: 75,
    },
    {
      hotStreak: true,
      wins: 14,
      veteran: false,
      losses: 5,
      rank: 'V',
      playerOrTeamName: 'Bronce5JajaSalu2',
      inactive: false,
      playerOrTeamId: '40520495',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: false,
      wins: 112,
      veteran: true,
      losses: 110,
      rank: 'I',
      playerOrTeamName: 'PowerOfArrow',
      inactive: false,
      playerOrTeamId: '49601958',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: false,
      wins: 93,
      veteran: false,
      losses: 92,
      rank: 'V',
      playerOrTeamName: 'xDovah',
      inactive: false,
      playerOrTeamId: '44513171',
      freshBlood: false,
      leaguePoints: 23,
    },
    {
      hotStreak: false,
      miniSeries: {
        wins: 0,
        losses: 0,
        target: 2,
        progress: 'NNN',
      },
      wins: 27,
      veteran: false,
      losses: 19,
      rank: 'II',
      playerOrTeamName: 'BenjiInvo',
      inactive: false,
      playerOrTeamId: '27400604',
      freshBlood: false,
      leaguePoints: 100,
    },
    {
      hotStreak: false,
      wins: 117,
      veteran: false,
      losses: 87,
      rank: 'II',
      playerOrTeamName: 'iLLiDane',
      inactive: false,
      playerOrTeamId: '67843433',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: false,
      wins: 82,
      veteran: false,
      losses: 73,
      rank: 'V',
      playerOrTeamName: 'Lady Arwem VI',
      inactive: false,
      playerOrTeamId: '89407334',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: false,
      wins: 252,
      veteran: false,
      losses: 233,
      rank: 'V',
      playerOrTeamName: 'Korsom',
      inactive: false,
      playerOrTeamId: '43275321',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: false,
      wins: 284,
      veteran: false,
      losses: 274,
      rank: 'V',
      playerOrTeamName: 'Snowbot',
      inactive: false,
      playerOrTeamId: '51012181',
      freshBlood: false,
      leaguePoints: 28,
    },
    {
      hotStreak: false,
      wins: 20,
      veteran: false,
      losses: 9,
      rank: 'V',
      playerOrTeamName: 'Worst Rengar',
      inactive: false,
      playerOrTeamId: '49672897',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: false,
      wins: 263,
      veteran: true,
      losses: 268,
      rank: 'III',
      playerOrTeamName: 'MEANGRY66',
      inactive: false,
      playerOrTeamId: '23136762',
      freshBlood: false,
      leaguePoints: 75,
    },
    {
      hotStreak: false,
      wins: 250,
      veteran: true,
      losses: 260,
      rank: 'III',
      playerOrTeamName: 'kchara',
      inactive: false,
      playerOrTeamId: '101476837',
      freshBlood: false,
      leaguePoints: 48,
    },
    {
      hotStreak: false,
      wins: 86,
      veteran: true,
      losses: 82,
      rank: 'I',
      playerOrTeamName: 'Cuka',
      inactive: false,
      playerOrTeamId: '22352422',
      freshBlood: false,
      leaguePoints: 84,
    },
    {
      hotStreak: false,
      wins: 47,
      veteran: false,
      losses: 48,
      rank: 'V',
      playerOrTeamName: 'PROJECT TROLL',
      inactive: false,
      playerOrTeamId: '19656800',
      freshBlood: false,
      leaguePoints: 77,
    },
    {
      hotStreak: false,
      wins: 76,
      veteran: true,
      losses: 89,
      rank: 'IV',
      playerOrTeamName: 'MyOhMy123',
      inactive: false,
      playerOrTeamId: '43124248',
      freshBlood: false,
      leaguePoints: 17,
    },
    {
      hotStreak: false,
      wins: 81,
      veteran: false,
      losses: 73,
      rank: 'I',
      playerOrTeamName: 'MurraykTz',
      inactive: false,
      playerOrTeamId: '91378183',
      freshBlood: false,
      leaguePoints: 57,
    },
    {
      hotStreak: false,
      wins: 6,
      veteran: false,
      losses: 4,
      rank: 'III',
      playerOrTeamName: 'Ang72',
      inactive: false,
      playerOrTeamId: '86279792',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: false,
      wins: 180,
      veteran: false,
      losses: 203,
      rank: 'V',
      playerOrTeamName: 'Ecatix',
      inactive: false,
      playerOrTeamId: '50157262',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: false,
      wins: 79,
      veteran: false,
      losses: 74,
      rank: 'IV',
      playerOrTeamName: 'Hi im Cirno',
      inactive: false,
      playerOrTeamId: '23842771',
      freshBlood: false,
      leaguePoints: 38,
    },
    {
      hotStreak: false,
      wins: 23,
      veteran: false,
      losses: 20,
      rank: 'I',
      playerOrTeamName: 'Tasemercy',
      inactive: false,
      playerOrTeamId: '90958166',
      freshBlood: false,
      leaguePoints: 75,
    },
    {
      hotStreak: false,
      wins: 7,
      veteran: false,
      losses: 4,
      rank: 'V',
      playerOrTeamName: 'Cranifex',
      inactive: false,
      playerOrTeamId: '35428352',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: false,
      wins: 272,
      veteran: false,
      losses: 238,
      rank: 'III',
      playerOrTeamName: 'Vinod003',
      inactive: false,
      playerOrTeamId: '42108001',
      freshBlood: false,
      leaguePoints: 3,
    },
    {
      hotStreak: false,
      wins: 3,
      veteran: false,
      losses: 9,
      rank: 'V',
      playerOrTeamName: 'DreaminAllstar',
      inactive: false,
      playerOrTeamId: '24384029',
      freshBlood: true,
      leaguePoints: 0,
    },
    {
      hotStreak: false,
      wins: 11,
      veteran: false,
      losses: 13,
      rank: 'IV',
      playerOrTeamName: 'Loopiee',
      inactive: false,
      playerOrTeamId: '37674082',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: false,
      wins: 89,
      veteran: true,
      losses: 83,
      rank: 'I',
      playerOrTeamName: 'STOP BANNlNG ME',
      inactive: false,
      playerOrTeamId: '100098200',
      freshBlood: false,
      leaguePoints: 75,
    },
    {
      hotStreak: false,
      wins: 38,
      veteran: false,
      losses: 29,
      rank: 'III',
      playerOrTeamName: 'St3dd1',
      inactive: false,
      playerOrTeamId: '49562346',
      freshBlood: false,
      leaguePoints: 60,
    },
    {
      hotStreak: false,
      wins: 25,
      veteran: false,
      losses: 27,
      rank: 'I',
      playerOrTeamName: 'JsyrBear',
      inactive: false,
      playerOrTeamId: '77187232',
      freshBlood: false,
      leaguePoints: 76,
    },
    {
      hotStreak: false,
      wins: 74,
      veteran: false,
      losses: 67,
      rank: 'V',
      playerOrTeamName: 'OneShotLux',
      inactive: false,
      playerOrTeamId: '96197091',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: false,
      wins: 128,
      veteran: true,
      losses: 137,
      rank: 'IV',
      playerOrTeamName: 'KahnTitan1',
      inactive: false,
      playerOrTeamId: '34101700',
      freshBlood: false,
      leaguePoints: 58,
    },
    {
      hotStreak: false,
      wins: 137,
      veteran: false,
      losses: 88,
      rank: 'I',
      playerOrTeamName: 'BestHambabaTR',
      inactive: false,
      playerOrTeamId: '96357031',
      freshBlood: false,
      leaguePoints: 75,
    },
    {
      hotStreak: false,
      wins: 80,
      veteran: false,
      losses: 82,
      rank: 'I',
      playerOrTeamName: 'Psykopat Klovn',
      inactive: false,
      playerOrTeamId: '94908545',
      freshBlood: false,
      leaguePoints: 75,
    },
    {
      hotStreak: false,
      wins: 99,
      veteran: true,
      losses: 120,
      rank: 'II',
      playerOrTeamName: 'Michelle',
      inactive: false,
      playerOrTeamId: '21887513',
      freshBlood: false,
      leaguePoints: 51,
    },
    {
      hotStreak: false,
      wins: 28,
      veteran: false,
      losses: 23,
      rank: 'III',
      playerOrTeamName: 'ponkersloor',
      inactive: false,
      playerOrTeamId: '19189861',
      freshBlood: false,
      leaguePoints: 8,
    },
    {
      hotStreak: false,
      wins: 48,
      veteran: false,
      losses: 23,
      rank: 'I',
      playerOrTeamName: 'LG RipV2',
      inactive: false,
      playerOrTeamId: '77747854',
      freshBlood: false,
      leaguePoints: 75,
    },
    {
      hotStreak: false,
      wins: 29,
      veteran: false,
      losses: 22,
      rank: 'II',
      playerOrTeamName: 'xRapidStar v2',
      inactive: false,
      playerOrTeamId: '97507089',
      freshBlood: false,
      leaguePoints: 47,
    },
    {
      hotStreak: false,
      wins: 66,
      veteran: false,
      losses: 54,
      rank: 'V',
      playerOrTeamName: 'chunknorriskille',
      inactive: false,
      playerOrTeamId: '33694365',
      freshBlood: false,
      leaguePoints: 5,
    },
    {
      hotStreak: false,
      miniSeries: {
        wins: 1,
        losses: 0,
        target: 2,
        progress: 'WNN',
      },
      wins: 14,
      veteran: false,
      losses: 17,
      rank: 'V',
      playerOrTeamName: 'Imelmann',
      inactive: false,
      playerOrTeamId: '21487818',
      freshBlood: false,
      leaguePoints: 100,
    },
    {
      hotStreak: false,
      wins: 328,
      veteran: true,
      losses: 306,
      rank: 'V',
      playerOrTeamName: 'Asyd',
      inactive: false,
      playerOrTeamId: '81225944',
      freshBlood: false,
      leaguePoints: 29,
    },
    {
      hotStreak: false,
      wins: 66,
      veteran: false,
      losses: 44,
      rank: 'V',
      playerOrTeamName: 'TheCometRock',
      inactive: false,
      playerOrTeamId: '36857607',
      freshBlood: false,
      leaguePoints: 74,
    },
    {
      hotStreak: false,
      wins: 6,
      veteran: false,
      losses: 4,
      rank: 'III',
      playerOrTeamName: 'Inaho Kaizuka',
      inactive: false,
      playerOrTeamId: '61277617',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: false,
      wins: 112,
      veteran: true,
      losses: 112,
      rank: 'I',
      playerOrTeamName: 'NICE 1V9 XD',
      inactive: false,
      playerOrTeamId: '94502785',
      freshBlood: false,
      leaguePoints: 38,
    },
    {
      hotStreak: false,
      wins: 145,
      veteran: true,
      losses: 136,
      rank: 'I',
      playerOrTeamName: 'SCHWARZNEGGER',
      inactive: false,
      playerOrTeamId: '23471810',
      freshBlood: false,
      leaguePoints: 75,
    },
    {
      hotStreak: false,
      wins: 56,
      veteran: false,
      losses: 49,
      rank: 'V',
      playerOrTeamName: 'juliaiwtb',
      inactive: false,
      playerOrTeamId: '70777357',
      freshBlood: false,
      leaguePoints: 5,
    },
    {
      hotStreak: false,
      wins: 224,
      veteran: true,
      losses: 201,
      rank: 'II',
      playerOrTeamName: 'vikern22',
      inactive: false,
      playerOrTeamId: '61430263',
      freshBlood: false,
      leaguePoints: 22,
    },
    {
      hotStreak: false,
      wins: 23,
      veteran: false,
      losses: 20,
      rank: 'III',
      playerOrTeamName: 'pastore195',
      inactive: false,
      playerOrTeamId: '38286898',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: false,
      wins: 203,
      veteran: true,
      losses: 200,
      rank: 'I',
      playerOrTeamName: 'EloBoostNeeded',
      inactive: false,
      playerOrTeamId: '94580317',
      freshBlood: false,
      leaguePoints: 75,
    },
    {
      hotStreak: false,
      wins: 108,
      veteran: true,
      losses: 110,
      rank: 'V',
      playerOrTeamName: 'xLorelei',
      inactive: false,
      playerOrTeamId: '81486290',
      freshBlood: false,
      leaguePoints: 1,
    },
    {
      hotStreak: false,
      wins: 8,
      veteran: false,
      losses: 2,
      rank: 'V',
      playerOrTeamName: 'Bekzide',
      inactive: false,
      playerOrTeamId: '21130877',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: false,
      wins: 106,
      veteran: false,
      losses: 99,
      rank: 'I',
      playerOrTeamName: 'ME BIG GUN',
      inactive: false,
      playerOrTeamId: '88387018',
      freshBlood: false,
      leaguePoints: 3,
    },
    {
      hotStreak: false,
      wins: 139,
      veteran: true,
      losses: 156,
      rank: 'V',
      playerOrTeamName: 'BisCieN',
      inactive: false,
      playerOrTeamId: '49717025',
      freshBlood: false,
      leaguePoints: 17,
    },
    {
      hotStreak: false,
      wins: 81,
      veteran: false,
      losses: 65,
      rank: 'I',
      playerOrTeamName: 'LG Bundy',
      inactive: false,
      playerOrTeamId: '30368983',
      freshBlood: false,
      leaguePoints: 83,
    },
    {
      hotStreak: false,
      wins: 21,
      veteran: false,
      losses: 33,
      rank: 'V',
      playerOrTeamName: 'MHExopowo',
      inactive: false,
      playerOrTeamId: '20737764',
      freshBlood: false,
      leaguePoints: 7,
    },
    {
      hotStreak: false,
      wins: 263,
      veteran: true,
      losses: 274,
      rank: 'V',
      playerOrTeamName: 'Steffenst17',
      inactive: false,
      playerOrTeamId: '28109643',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: false,
      wins: 229,
      veteran: false,
      losses: 216,
      rank: 'V',
      playerOrTeamName: 'Empereur Teud',
      inactive: false,
      playerOrTeamId: '54838375',
      freshBlood: false,
      leaguePoints: 92,
    },
    {
      hotStreak: false,
      wins: 50,
      veteran: false,
      losses: 48,
      rank: 'V',
      playerOrTeamName: 'G0LdEnIcE',
      inactive: false,
      playerOrTeamId: '61060069',
      freshBlood: false,
      leaguePoints: 20,
    },
    {
      hotStreak: false,
      wins: 36,
      veteran: false,
      losses: 26,
      rank: 'V',
      playerOrTeamName: 'OG joeri',
      inactive: false,
      playerOrTeamId: '31975031',
      freshBlood: false,
      leaguePoints: 21,
    },
    {
      hotStreak: false,
      wins: 37,
      veteran: false,
      losses: 57,
      rank: 'V',
      playerOrTeamName: 'True ScAreCroW',
      inactive: false,
      playerOrTeamId: '21447098',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: false,
      wins: 159,
      veteran: false,
      losses: 185,
      rank: 'V',
      playerOrTeamName: 'iTz PsYchoTriiX',
      inactive: false,
      playerOrTeamId: '30719500',
      freshBlood: false,
      leaguePoints: 23,
    },
    {
      hotStreak: false,
      wins: 23,
      veteran: false,
      losses: 10,
      rank: 'V',
      playerOrTeamName: 'stixiz',
      inactive: false,
      playerOrTeamId: '34100780',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: true,
      wins: 16,
      veteran: false,
      losses: 4,
      rank: 'I',
      playerOrTeamName: 'sovsemad',
      inactive: false,
      playerOrTeamId: '20896374',
      freshBlood: false,
      leaguePoints: 75,
    },
    {
      hotStreak: false,
      wins: 185,
      veteran: false,
      losses: 150,
      rank: 'II',
      playerOrTeamName: '0Kai0',
      inactive: false,
      playerOrTeamId: '75291599',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: false,
      wins: 21,
      veteran: false,
      losses: 21,
      rank: 'III',
      playerOrTeamName: 'chill ionix',
      inactive: false,
      playerOrTeamId: '62907190',
      freshBlood: false,
      leaguePoints: 21,
    },
    {
      hotStreak: false,
      wins: 67,
      veteran: true,
      losses: 72,
      rank: 'V',
      playerOrTeamName: 'Risenivy',
      inactive: false,
      playerOrTeamId: '89487872',
      freshBlood: false,
      leaguePoints: 75,
    },
    {
      hotStreak: false,
      wins: 256,
      veteran: false,
      losses: 252,
      rank: 'V',
      playerOrTeamName: 'DayZ Me Trolling',
      inactive: false,
      playerOrTeamId: '64318341',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: false,
      wins: 184,
      veteran: true,
      losses: 131,
      rank: 'I',
      playerOrTeamName: 'Jjunkeer10',
      inactive: false,
      playerOrTeamId: '60962088',
      freshBlood: false,
      leaguePoints: 72,
    },
    {
      hotStreak: false,
      wins: 1039,
      veteran: true,
      losses: 998,
      rank: 'IV',
      playerOrTeamName: 'xxNjoten2000xx ',
      inactive: false,
      playerOrTeamId: '70221287',
      freshBlood: false,
      leaguePoints: 18,
    },
    {
      hotStreak: false,
      wins: 63,
      veteran: false,
      losses: 62,
      rank: 'I',
      playerOrTeamName: 'mls5g',
      inactive: false,
      playerOrTeamId: '85720334',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: false,
      wins: 15,
      veteran: false,
      losses: 8,
      rank: 'IV',
      playerOrTeamName: 'GVT Blackbox',
      inactive: false,
      playerOrTeamId: '35130920',
      freshBlood: false,
      leaguePoints: 9,
    },
    {
      hotStreak: false,
      wins: 14,
      veteran: false,
      losses: 8,
      rank: 'II',
      playerOrTeamName: 'ItsNotMike',
      inactive: false,
      playerOrTeamId: '52761387',
      freshBlood: false,
      leaguePoints: 82,
    },
    {
      hotStreak: false,
      wins: 47,
      veteran: false,
      losses: 29,
      rank: 'I',
      playerOrTeamName: 'KARMA SO BROKEN',
      inactive: false,
      playerOrTeamId: '60900163',
      freshBlood: false,
      leaguePoints: 75,
    },
    {
      hotStreak: false,
      wins: 61,
      veteran: false,
      losses: 45,
      rank: 'I',
      playerOrTeamName: 'Teguesnanth',
      inactive: false,
      playerOrTeamId: '93629118',
      freshBlood: false,
      leaguePoints: 75,
    },
    {
      hotStreak: false,
      wins: 11,
      veteran: false,
      losses: 9,
      rank: 'IV',
      playerOrTeamName: 'Flamedji',
      inactive: false,
      playerOrTeamId: '95897578',
      freshBlood: false,
      leaguePoints: 62,
    },
    {
      hotStreak: false,
      wins: 199,
      veteran: false,
      losses: 213,
      rank: 'I',
      playerOrTeamName: 'Born to be Faker',
      inactive: false,
      playerOrTeamId: '95137168',
      freshBlood: false,
      leaguePoints: 59,
    },
    {
      hotStreak: true,
      miniSeries: {
        wins: 1,
        losses: 0,
        target: 2,
        progress: 'WNN',
      },
      wins: 22,
      veteran: false,
      losses: 23,
      rank: 'IV',
      playerOrTeamName: 'Cocornitho',
      inactive: false,
      playerOrTeamId: '44934130',
      freshBlood: false,
      leaguePoints: 100,
    },
    {
      hotStreak: false,
      wins: 42,
      veteran: false,
      losses: 57,
      rank: 'V',
      playerOrTeamName: 'DJ WasaBi',
      inactive: false,
      playerOrTeamId: '26378641',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: false,
      wins: 13,
      veteran: false,
      losses: 7,
      rank: 'III',
      playerOrTeamName: 'Davidich98',
      inactive: false,
      playerOrTeamId: '53151998',
      freshBlood: false,
      leaguePoints: 76,
    },
    {
      hotStreak: false,
      wins: 87,
      veteran: false,
      losses: 90,
      rank: 'IV',
      playerOrTeamName: 'EPF Touni',
      inactive: false,
      playerOrTeamId: '60988480',
      freshBlood: false,
      leaguePoints: 21,
    },
    {
      hotStreak: false,
      wins: 32,
      veteran: false,
      losses: 18,
      rank: 'II',
      playerOrTeamName: 'BloodWorkXGaming',
      inactive: false,
      playerOrTeamId: '38409719',
      freshBlood: false,
      leaguePoints: 38,
    },
    {
      hotStreak: false,
      wins: 21,
      veteran: false,
      losses: 30,
      rank: 'I',
      playerOrTeamName: 'WaouwBlink',
      inactive: false,
      playerOrTeamId: '84647843',
      freshBlood: false,
      leaguePoints: 75,
    },
    {
      hotStreak: false,
      wins: 137,
      veteran: false,
      losses: 128,
      rank: 'I',
      playerOrTeamName: 'Simberg',
      inactive: false,
      playerOrTeamId: '24476300',
      freshBlood: false,
      leaguePoints: 75,
    },
    {
      hotStreak: false,
      wins: 193,
      veteran: false,
      losses: 180,
      rank: 'V',
      playerOrTeamName: 'LordPerse',
      inactive: false,
      playerOrTeamId: '19153861',
      freshBlood: false,
      leaguePoints: 20,
    },
    {
      hotStreak: false,
      wins: 65,
      veteran: false,
      losses: 66,
      rank: 'I',
      playerOrTeamName: 'Xrkeh',
      inactive: false,
      playerOrTeamId: '24003950',
      freshBlood: false,
      leaguePoints: 75,
    },
    {
      hotStreak: false,
      wins: 72,
      veteran: true,
      losses: 78,
      rank: 'I',
      playerOrTeamName: 'EU is anti white',
      inactive: false,
      playerOrTeamId: '19836134',
      freshBlood: false,
      leaguePoints: 37,
    },
    {
      hotStreak: false,
      wins: 452,
      veteran: true,
      losses: 435,
      rank: 'III',
      playerOrTeamName: 'La Mère à Coco',
      inactive: false,
      playerOrTeamId: '42896939',
      freshBlood: false,
      leaguePoints: 70,
    },
    {
      hotStreak: false,
      wins: 6,
      veteran: false,
      losses: 8,
      rank: 'I',
      playerOrTeamName: 'BobbbCartmaN',
      inactive: false,
      playerOrTeamId: '76797387',
      freshBlood: false,
      leaguePoints: 75,
    },
    {
      hotStreak: false,
      miniSeries: {
        wins: 1,
        losses: 1,
        target: 2,
        progress: 'WLN',
      },
      wins: 196,
      veteran: true,
      losses: 215,
      rank: 'V',
      playerOrTeamName: 'CiA121',
      inactive: false,
      playerOrTeamId: '54366893',
      freshBlood: false,
      leaguePoints: 83,
    },
    {
      hotStreak: false,
      wins: 18,
      veteran: false,
      losses: 10,
      rank: 'V',
      playerOrTeamName: 'Octovannox',
      inactive: false,
      playerOrTeamId: '96308866',
      freshBlood: false,
      leaguePoints: 43,
    },
    {
      hotStreak: false,
      wins: 70,
      veteran: false,
      losses: 51,
      rank: 'I',
      playerOrTeamName: 'REGGEA REFORMED',
      inactive: false,
      playerOrTeamId: '98838723',
      freshBlood: false,
      leaguePoints: 75,
    },
    {
      hotStreak: false,
      wins: 254,
      veteran: true,
      losses: 260,
      rank: 'III',
      playerOrTeamName: 'jte roule dessus',
      inactive: false,
      playerOrTeamId: '36959140',
      freshBlood: false,
      leaguePoints: 36,
    },
    {
      hotStreak: false,
      wins: 242,
      veteran: true,
      losses: 233,
      rank: 'III',
      playerOrTeamName: 'Sir Hywen',
      inactive: false,
      playerOrTeamId: '39240048',
      freshBlood: false,
      leaguePoints: 22,
    },
    {
      hotStreak: false,
      wins: 65,
      veteran: false,
      losses: 53,
      rank: 'I',
      playerOrTeamName: 'Insomný',
      inactive: false,
      playerOrTeamId: '94749680',
      freshBlood: false,
      leaguePoints: 75,
    },
    {
      hotStreak: false,
      wins: 9,
      veteran: false,
      losses: 8,
      rank: 'III',
      playerOrTeamName: 'D i G',
      inactive: false,
      playerOrTeamId: '36267799',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: false,
      wins: 6,
      veteran: false,
      losses: 6,
      rank: 'IV',
      playerOrTeamName: 'dakkkc',
      inactive: false,
      playerOrTeamId: '42279018',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: false,
      wins: 180,
      veteran: true,
      losses: 159,
      rank: 'II',
      playerOrTeamName: 'Geistyan',
      inactive: false,
      playerOrTeamId: '80279541',
      freshBlood: false,
      leaguePoints: 70,
    },
    {
      hotStreak: false,
      wins: 70,
      veteran: true,
      losses: 61,
      rank: 'I',
      playerOrTeamName: 'Groobles',
      inactive: false,
      playerOrTeamId: '52731906',
      freshBlood: false,
      leaguePoints: 87,
    },
    {
      hotStreak: false,
      wins: 133,
      veteran: false,
      losses: 90,
      rank: 'V',
      playerOrTeamName: 'DasiN',
      inactive: false,
      playerOrTeamId: '86697757',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: false,
      wins: 113,
      veteran: false,
      losses: 114,
      rank: 'V',
      playerOrTeamName: 'Big Bad Senpai',
      inactive: false,
      playerOrTeamId: '40939287',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: false,
      wins: 15,
      veteran: false,
      losses: 18,
      rank: 'V',
      playerOrTeamName: 'TETRARIS',
      inactive: false,
      playerOrTeamId: '44748597',
      freshBlood: false,
      leaguePoints: 80,
    },
    {
      hotStreak: false,
      wins: 239,
      veteran: false,
      losses: 213,
      rank: 'I',
      playerOrTeamName: '458',
      inactive: false,
      playerOrTeamId: '98407096',
      freshBlood: false,
      leaguePoints: 75,
    },
    {
      hotStreak: true,
      miniSeries: {
        wins: 0,
        losses: 0,
        target: 2,
        progress: 'NNN',
      },
      wins: 29,
      veteran: false,
      losses: 20,
      rank: 'II',
      playerOrTeamName: 'ayyy LOMO',
      inactive: false,
      playerOrTeamId: '79439226',
      freshBlood: false,
      leaguePoints: 100,
    },
    {
      hotStreak: false,
      wins: 31,
      veteran: false,
      losses: 43,
      rank: 'IV',
      playerOrTeamName: 'Pirenato',
      inactive: false,
      playerOrTeamId: '37647687',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: false,
      wins: 50,
      veteran: false,
      losses: 27,
      rank: 'I',
      playerOrTeamName: 'MaxPecks',
      inactive: false,
      playerOrTeamId: '49683293',
      freshBlood: false,
      leaguePoints: 75,
    },
    {
      hotStreak: false,
      wins: 46,
      veteran: false,
      losses: 33,
      rank: 'V',
      playerOrTeamName: 'Lou the Lion',
      inactive: false,
      playerOrTeamId: '34910730',
      freshBlood: false,
      leaguePoints: 35,
    },
    {
      hotStreak: false,
      wins: 152,
      veteran: false,
      losses: 156,
      rank: 'V',
      playerOrTeamName: 'FNC ShadOwStaR',
      inactive: false,
      playerOrTeamId: '49217789',
      freshBlood: false,
      leaguePoints: 15,
    },
    {
      hotStreak: false,
      wins: 55,
      veteran: false,
      losses: 51,
      rank: 'V',
      playerOrTeamName: 'RóïLèR',
      inactive: false,
      playerOrTeamId: '36476975',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: false,
      wins: 53,
      veteran: false,
      losses: 58,
      rank: 'V',
      playerOrTeamName: 'kushbringer',
      inactive: false,
      playerOrTeamId: '24686092',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: false,
      wins: 28,
      veteran: false,
      losses: 28,
      rank: 'V',
      playerOrTeamName: 'Smthelse',
      inactive: false,
      playerOrTeamId: '19996310',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: false,
      miniSeries: {
        wins: 0,
        losses: 0,
        target: 3,
        progress: 'NNNNN',
      },
      wins: 36,
      veteran: false,
      losses: 20,
      rank: 'I',
      playerOrTeamName: 'Dr Djé',
      inactive: false,
      playerOrTeamId: '38788527',
      freshBlood: false,
      leaguePoints: 100,
    },
    {
      hotStreak: true,
      wins: 161,
      veteran: true,
      losses: 186,
      rank: 'I',
      playerOrTeamName: 'cyjoub',
      inactive: false,
      playerOrTeamId: '35877721',
      freshBlood: false,
      leaguePoints: 75,
    },
    {
      hotStreak: false,
      wins: 691,
      veteran: true,
      losses: 724,
      rank: 'V',
      playerOrTeamName: 'Makosso',
      inactive: false,
      playerOrTeamId: '57638055',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: false,
      wins: 70,
      veteran: false,
      losses: 72,
      rank: 'V',
      playerOrTeamName: 'FNC Baby Gollum',
      inactive: false,
      playerOrTeamId: '30900357',
      freshBlood: false,
      leaguePoints: 66,
    },
    {
      hotStreak: true,
      miniSeries: {
        wins: 1,
        losses: 0,
        target: 2,
        progress: 'WNN',
      },
      wins: 301,
      veteran: true,
      losses: 300,
      rank: 'V',
      playerOrTeamName: '3DM PhoeniX v2',
      inactive: false,
      playerOrTeamId: '29507372',
      freshBlood: false,
      leaguePoints: 100,
    },
    {
      hotStreak: false,
      wins: 93,
      veteran: false,
      losses: 74,
      rank: 'V',
      playerOrTeamName: 'Starlax77',
      inactive: false,
      playerOrTeamId: '85669716',
      freshBlood: false,
      leaguePoints: 17,
    },
    {
      hotStreak: false,
      wins: 126,
      veteran: false,
      losses: 119,
      rank: 'V',
      playerOrTeamName: 'BeGoku',
      inactive: false,
      playerOrTeamId: '52446557',
      freshBlood: false,
      leaguePoints: 21,
    },
    {
      hotStreak: false,
      wins: 420,
      veteran: false,
      losses: 430,
      rank: 'III',
      playerOrTeamName: 'BennyTheButcher',
      inactive: false,
      playerOrTeamId: '43973345',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: false,
      wins: 108,
      veteran: false,
      losses: 98,
      rank: 'IV',
      playerOrTeamName: 'Nours25',
      inactive: false,
      playerOrTeamId: '43598064',
      freshBlood: false,
      leaguePoints: 80,
    },
    {
      hotStreak: false,
      wins: 75,
      veteran: false,
      losses: 52,
      rank: 'I',
      playerOrTeamName: 'Uçan Türk',
      inactive: false,
      playerOrTeamId: '73677464',
      freshBlood: false,
      leaguePoints: 75,
    },
    {
      hotStreak: true,
      wins: 25,
      veteran: false,
      losses: 28,
      rank: 'V',
      playerOrTeamName: 'Hummel97',
      inactive: false,
      playerOrTeamId: '23529022',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: false,
      wins: 419,
      veteran: true,
      losses: 443,
      rank: 'III',
      playerOrTeamName: 'Un cochon Halal',
      inactive: false,
      playerOrTeamId: '50449823',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: false,
      wins: 6,
      veteran: false,
      losses: 5,
      rank: 'V',
      playerOrTeamName: 'Xeptlolz',
      inactive: false,
      playerOrTeamId: '34200813',
      freshBlood: false,
      leaguePoints: 26,
    },
    {
      hotStreak: false,
      wins: 259,
      veteran: true,
      losses: 252,
      rank: 'IV',
      playerOrTeamName: 'STUCKINYOURMUM',
      inactive: false,
      playerOrTeamId: '44398605',
      freshBlood: false,
      leaguePoints: 15,
    },
    {
      hotStreak: false,
      wins: 227,
      veteran: true,
      losses: 216,
      rank: 'III',
      playerOrTeamName: 'Akíyama Mio',
      inactive: false,
      playerOrTeamId: '37897703',
      freshBlood: false,
      leaguePoints: 21,
    },
    {
      hotStreak: false,
      wins: 59,
      veteran: false,
      losses: 42,
      rank: 'V',
      playerOrTeamName: 'TheTacoManZ',
      inactive: false,
      playerOrTeamId: '72732966',
      freshBlood: false,
      leaguePoints: 21,
    },
    {
      hotStreak: false,
      wins: 103,
      veteran: true,
      losses: 114,
      rank: 'I',
      playerOrTeamName: '211298',
      inactive: false,
      playerOrTeamId: '78617431',
      freshBlood: false,
      leaguePoints: 75,
    },
    {
      hotStreak: false,
      wins: 127,
      veteran: true,
      losses: 106,
      rank: 'II',
      playerOrTeamName: 'AVDutch',
      inactive: false,
      playerOrTeamId: '37888494',
      freshBlood: false,
      leaguePoints: 55,
    },
    {
      hotStreak: false,
      wins: 7,
      veteran: false,
      losses: 4,
      rank: 'III',
      playerOrTeamName: 'ibliopolic',
      inactive: false,
      playerOrTeamId: '67035483',
      freshBlood: false,
      leaguePoints: 24,
    },
    {
      hotStreak: false,
      wins: 240,
      veteran: false,
      losses: 265,
      rank: 'V',
      playerOrTeamName: 'PoR Dark Riku',
      inactive: false,
      playerOrTeamId: '29890960',
      freshBlood: false,
      leaguePoints: 32,
    },
    {
      hotStreak: false,
      wins: 63,
      veteran: false,
      losses: 56,
      rank: 'II',
      playerOrTeamName: 'KayPflaume',
      inactive: false,
      playerOrTeamId: '20430695',
      freshBlood: false,
      leaguePoints: 1,
    },
    {
      hotStreak: false,
      miniSeries: {
        wins: 1,
        losses: 0,
        target: 2,
        progress: 'WNN',
      },
      wins: 61,
      veteran: false,
      losses: 58,
      rank: 'V',
      playerOrTeamName: 'Regenbaum',
      inactive: false,
      playerOrTeamId: '27652090',
      freshBlood: false,
      leaguePoints: 100,
    },
    {
      hotStreak: false,
      wins: 67,
      veteran: false,
      losses: 42,
      rank: 'I',
      playerOrTeamName: 'Impertinente',
      inactive: false,
      playerOrTeamId: '20894768',
      freshBlood: false,
      leaguePoints: 75,
    },
    {
      hotStreak: false,
      wins: 68,
      veteran: false,
      losses: 70,
      rank: 'V',
      playerOrTeamName: 'ChickenPunk',
      inactive: false,
      playerOrTeamId: '25934124',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: true,
      wins: 105,
      veteran: true,
      losses: 111,
      rank: 'II',
      playerOrTeamName: 'Holy Lucian',
      inactive: false,
      playerOrTeamId: '82649107',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: false,
      wins: 22,
      veteran: false,
      losses: 15,
      rank: 'I',
      playerOrTeamName: 'LG Metaltooth',
      inactive: false,
      playerOrTeamId: '30660221',
      freshBlood: false,
      leaguePoints: 31,
    },
    {
      hotStreak: false,
      wins: 48,
      veteran: false,
      losses: 21,
      rank: 'I',
      playerOrTeamName: 'A WILD HlTLER XD',
      inactive: false,
      playerOrTeamId: '94828287',
      freshBlood: false,
      leaguePoints: 75,
    },
    {
      hotStreak: false,
      wins: 72,
      veteran: true,
      losses: 66,
      rank: 'II',
      playerOrTeamName: 'SheWasNot14',
      inactive: false,
      playerOrTeamId: '98197222',
      freshBlood: false,
      leaguePoints: 34,
    },
    {
      hotStreak: false,
      wins: 323,
      veteran: false,
      losses: 291,
      rank: 'III',
      playerOrTeamName: 'Porkepik',
      inactive: false,
      playerOrTeamId: '80566955',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: false,
      wins: 52,
      veteran: false,
      losses: 58,
      rank: 'IV',
      playerOrTeamName: 'KaYii',
      inactive: false,
      playerOrTeamId: '95167643',
      freshBlood: false,
      leaguePoints: 11,
    },
    {
      hotStreak: false,
      wins: 19,
      veteran: false,
      losses: 33,
      rank: 'I',
      playerOrTeamName: 'Rina Ceket Sever',
      inactive: false,
      playerOrTeamId: '92807182',
      freshBlood: false,
      leaguePoints: 52,
    },
    {
      hotStreak: false,
      wins: 120,
      veteran: true,
      losses: 117,
      rank: 'I',
      playerOrTeamName: 'Tanzah TOP',
      inactive: false,
      playerOrTeamId: '101207111',
      freshBlood: false,
      leaguePoints: 26,
    },
    {
      hotStreak: false,
      wins: 248,
      veteran: true,
      losses: 251,
      rank: 'II',
      playerOrTeamName: 'Zeplix',
      inactive: false,
      playerOrTeamId: '20848230',
      freshBlood: false,
      leaguePoints: 75,
    },
    {
      hotStreak: false,
      wins: 332,
      veteran: true,
      losses: 312,
      rank: 'IV',
      playerOrTeamName: 'Bakedhoven',
      inactive: false,
      playerOrTeamId: '28958577',
      freshBlood: false,
      leaguePoints: 17,
    },
    {
      hotStreak: false,
      wins: 254,
      veteran: false,
      losses: 261,
      rank: 'V',
      playerOrTeamName: 'Ira Seratum',
      inactive: false,
      playerOrTeamId: '33674739',
      freshBlood: false,
      leaguePoints: 48,
    },
    {
      hotStreak: false,
      miniSeries: {
        wins: 2,
        losses: 2,
        target: 3,
        progress: 'WWLLN',
      },
      wins: 173,
      veteran: true,
      losses: 176,
      rank: 'I',
      playerOrTeamName: 'Hawkence',
      inactive: false,
      playerOrTeamId: '26185337',
      freshBlood: false,
      leaguePoints: 100,
    },
    {
      hotStreak: false,
      wins: 53,
      veteran: false,
      losses: 30,
      rank: 'I',
      playerOrTeamName: 'Jbouamapiss',
      inactive: false,
      playerOrTeamId: '92000829',
      freshBlood: false,
      leaguePoints: 75,
    },
    {
      hotStreak: false,
      miniSeries: {
        wins: 1,
        losses: 1,
        target: 2,
        progress: 'WLN',
      },
      wins: 21,
      veteran: false,
      losses: 15,
      rank: 'IV',
      playerOrTeamName: 'lPrGhJoyce',
      inactive: false,
      playerOrTeamId: '26267178',
      freshBlood: false,
      leaguePoints: 100,
    },
    {
      hotStreak: false,
      wins: 111,
      veteran: true,
      losses: 127,
      rank: 'II',
      playerOrTeamName: 'Kiba104',
      inactive: false,
      playerOrTeamId: '24725382',
      freshBlood: false,
      leaguePoints: 92,
    },
    {
      hotStreak: false,
      wins: 293,
      veteran: true,
      losses: 302,
      rank: 'I',
      playerOrTeamName: 'IvanRUSSAGENT007',
      inactive: false,
      playerOrTeamId: '23506641',
      freshBlood: false,
      leaguePoints: 75,
    },
    {
      hotStreak: false,
      wins: 441,
      veteran: false,
      losses: 451,
      rank: 'IV',
      playerOrTeamName: 'Odins Raven',
      inactive: false,
      playerOrTeamId: '72233653',
      freshBlood: false,
      leaguePoints: 37,
    },
    {
      hotStreak: false,
      wins: 216,
      veteran: true,
      losses: 240,
      rank: 'II',
      playerOrTeamName: 'zZantino ',
      inactive: false,
      playerOrTeamId: '30800914',
      freshBlood: false,
      leaguePoints: 15,
    },
    {
      hotStreak: false,
      wins: 192,
      veteran: true,
      losses: 168,
      rank: 'I',
      playerOrTeamName: 'Tylerrfkin1',
      inactive: false,
      playerOrTeamId: '37816960',
      freshBlood: false,
      leaguePoints: 56,
    },
    {
      hotStreak: false,
      wins: 98,
      veteran: false,
      losses: 81,
      rank: 'V',
      playerOrTeamName: 'Elley152',
      inactive: false,
      playerOrTeamId: '54527963',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: false,
      wins: 212,
      veteran: true,
      losses: 213,
      rank: 'I',
      playerOrTeamName: 'Point G Fragile',
      inactive: false,
      playerOrTeamId: '91159121',
      freshBlood: false,
      leaguePoints: 75,
    },
    {
      hotStreak: false,
      wins: 503,
      veteran: true,
      losses: 511,
      rank: 'II',
      playerOrTeamName: 's0yb0y',
      inactive: false,
      playerOrTeamId: '29129183',
      freshBlood: false,
      leaguePoints: 97,
    },
    {
      hotStreak: true,
      wins: 44,
      veteran: false,
      losses: 27,
      rank: 'I',
      playerOrTeamName: 'I give you Candy',
      inactive: false,
      playerOrTeamId: '20932125',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: false,
      wins: 77,
      veteran: false,
      losses: 56,
      rank: 'III',
      playerOrTeamName: 'Thręsh Guy',
      inactive: false,
      playerOrTeamId: '65871030',
      freshBlood: false,
      leaguePoints: 25,
    },
    {
      hotStreak: false,
      wins: 186,
      veteran: true,
      losses: 212,
      rank: 'V',
      playerOrTeamName: 'Dubioushunter',
      inactive: false,
      playerOrTeamId: '79380472',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: false,
      wins: 56,
      veteran: false,
      losses: 47,
      rank: 'I',
      playerOrTeamName: 'I Love Jocks',
      inactive: false,
      playerOrTeamId: '37866031',
      freshBlood: false,
      leaguePoints: 98,
    },
    {
      hotStreak: false,
      wins: 9,
      veteran: false,
      losses: 1,
      rank: 'II',
      playerOrTeamName: 'FCPorto2004',
      inactive: false,
      playerOrTeamId: '96488052',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: false,
      wins: 183,
      veteran: false,
      losses: 170,
      rank: 'V',
      playerOrTeamName: 'I bims 1 Annie',
      inactive: false,
      playerOrTeamId: '85036960',
      freshBlood: false,
      leaguePoints: 10,
    },
    {
      hotStreak: false,
      wins: 190,
      veteran: true,
      losses: 198,
      rank: 'V',
      playerOrTeamName: 'Br0nzeSplash',
      inactive: false,
      playerOrTeamId: '71317101',
      freshBlood: false,
      leaguePoints: 75,
    },
    {
      hotStreak: false,
      wins: 354,
      veteran: true,
      losses: 336,
      rank: 'III',
      playerOrTeamName: 'Dridridrëam',
      inactive: false,
      playerOrTeamId: '93930363',
      freshBlood: false,
      leaguePoints: 31,
    },
    {
      hotStreak: false,
      wins: 109,
      veteran: false,
      losses: 99,
      rank: 'I',
      playerOrTeamName: 'BioCellucor IF',
      inactive: false,
      playerOrTeamId: '24186168',
      freshBlood: false,
      leaguePoints: 29,
    },
    {
      hotStreak: false,
      wins: 105,
      veteran: false,
      losses: 76,
      rank: 'I',
      playerOrTeamName: 'gWelFlisa',
      inactive: false,
      playerOrTeamId: '92517057',
      freshBlood: false,
      leaguePoints: 75,
    },
    {
      hotStreak: false,
      wins: 54,
      veteran: false,
      losses: 28,
      rank: 'I',
      playerOrTeamName: 'IngemardBl',
      inactive: false,
      playerOrTeamId: '94727734',
      freshBlood: false,
      leaguePoints: 75,
    },
    {
      hotStreak: false,
      wins: 119,
      veteran: false,
      losses: 125,
      rank: 'V',
      playerOrTeamName: 'lalelu712',
      inactive: false,
      playerOrTeamId: '29861658',
      freshBlood: false,
      leaguePoints: 2,
    },
    {
      hotStreak: false,
      wins: 53,
      veteran: false,
      losses: 45,
      rank: 'V',
      playerOrTeamName: 'Kidbb',
      inactive: false,
      playerOrTeamId: '82589976',
      freshBlood: false,
      leaguePoints: 0,
    },
    {
      hotStreak: false,
      wins: 195,
      veteran: true,
      losses: 173,
      rank: 'V',
      playerOrTeamName: 'WstAngelfox',
      inactive: false,
      playerOrTeamId: '25813747',
      freshBlood: false,
      leaguePoints: 45,
    },
    {
      hotStreak: false,
      wins: 408,
      veteran: true,
      losses: 407,
      rank: 'IV',
      playerOrTeamName: 'Str1p3r',
      inactive: false,
      playerOrTeamId: '65961752',
      freshBlood: false,
      leaguePoints: 43,
    },
  ],
};
